### PR TITLE
fix: mysql string column length is required

### PR DESCRIPTION
**Pull request by paweldudzinski**
## Issue
`VARCHAR` lenght is require in MySQL 5.7

## Error
"VARCHAR requires a length on dialect %s" % self.dialect.name
sqlalchemy.exc.CompileError: (in table 'workflows', column 'name'): VARCHAR requires a length on dialect mysql

## Reproduction
Put `DIRECTOR_DATABASE_URI=<proper_mysql_5.7_uri>` into `.env` file
Run `director db upgrade`

## Fix suggestion
Added fixed length to `sa.String()` occurrences

### CODE REVIEW

**Comment by ncrocfer** [comment]
Hello @paweldudzinski ,

First of all thank you for this PR !

Just by curiosity, why did you choose `128m` in size ? Is-it a best-practice or something like that ?

**Comment by paweldudzinski** [comment]
hi @ncrocfer !!!
> Just by curiosity, why did you choose `128m` in size ? Is-it a best-practice or something like that ?
It was arbitrarily chosen, nothing behind this except my opinion that it would be enough capacity to store the data.

**Comment by maximecaruchet** [comment]
Hello,

Sorry for the delay here, I'm testing your pull request in order to merge it. A few minor things I noticed:

* I suppose it would be better to have 255 instead of 128 in your VARCHAR lengths (according to this: https://stackoverflow.com/questions/1217466/is-there-a-good-reason-i-see-varchar255-used-so-often-as-opposed-to-another-l). This would be closer to what we had before (no length specified) I guess.
* I couldn't run `director db upgrade` directly. I needed to run the following commands: `sudo apt-get install python3-dev default-libmysqlclient-dev build-essential` and then `pip install mysqlclient`. I guess the apt-get install command should be added to the README and the mysqlclient python package should be added to requirements.txt (here is my version: `mysqlclient==2.0.1`)

**Review by maximecaruchet — CHANGES_REQUESTED** [review]
Feedback/Changes to do are in my previous comment :)

**Comment by anthonyolea** [comment]
Hello :-)
Beside, can you sign-off your commit (see: https://github.com/ovh/celery-director/blob/master/CONTRIBUTING.md)

**Comment by maximecaruchet** [comment]
@anthonyolea also mentioned that maybe `pip install mysql-connector-python` with a connection string starting like that: `mysql+mysqlconnector://` might work. I tested it and indeed it works, so it may be better than what I said initially (this way we don't have to install apt packages). Just update the readme to say that we can use mysql with the `mysql+mysqlconnector://` connection string, and add `mysql-connector-python==8.0.21` to the requirements (instead of `mysqlclient`)

**Comment by paweldudzinski** [comment]
@maximecaruchet Thanks for the comments. Indeed it'd be better to alight with the default `String` length when length is not specified. This is updated. 
Also I added the `mysql-connector-python==8.0.21` to the `requirements.txt` yet I think it would be better to put the explanation how to create a connection string with `mysql+mysqlconnector://` here: https://ovh.github.io/celery-director/quickstart/ as `README.md` has no `Configure the database` section.
Also I tested `directory up database` command with `mysql://` and mysql+mysqlconnector://` and it works both ways.

**Review by maximecaruchet — APPROVED** [review]
Hello, looks good to me now, we will update the docs after merging your PR on our side. Thank a lot for your contribution! :)

**Pull request merged**
