### PR TITLE
Bugfix: updating flask package version and dependencies

### PR DESCRIPTION
**Pull request by CodePint**
fix: updating flask package version and dependencies

ref issue:
https://github.com/ovh/celery-director/issues/125
ref flask 2.0.0 release:
https://flask.palletsprojects.com/en/2.0.x/changes/#version-2-0-0

- Flask upgraded from `==1.1.1` to `==2.0.0`
- Werkzeug upgraded from `==1.0.1` to `==2.0.0`
- click upgraded from `==7.0` to `==7.1.2`

Signed-off-by: George Eddie geddie@linius.com

### CODE REVIEW

**Review by ncrocfer — CHANGES_REQUESTED** [review]
Can you please pin your requirements? `Flask==xxx` for instance.

**Comment by ncrocfer** [comment]
For information we just pinned `itsdangerous` in another PR to unblock it (see https://github.com/ovh/celery-director/pull/122/commits/9e554b11512c87c81b2e8e3d91f2b205cb1baae9).

When you will pin Flask, Werkzeug and click requirements please remove itsdangerous ;)

**Comment by CodePint** [comment]
> Can you please pin your requirements? `Flask==xxx` for instance.

I think there is benefit to being more flexible on requirement versions. Maybe one to consider.
Anyway I've rebased off of master and force pushed the change with the requirements pinned

**Comment by CodePint** [comment]
Are you able to create a new release once this is merged?

**Comment by CodePint** [comment]
> Personally I don't agree with that, when I deploy an application I want to be sure my builds are predictable and deterministic. If you don't pin your requirements it's not possible wink

Yeah I understand that argument and agree with the sentiment.
I just feel that should be down to the application which uses the framework to ensure this by using something like pip-compile.

Anyway, happy to defer here shall we get this merged :) ?

**Comment by ncrocfer** [comment]
We'll merge it tomorrow.
And for the new release we have to review and merge other PRs before it.

**Comment by CodePint** [comment]
> 

Okay understood, will check in tomorrow. I've got one other PR open and a few more to raise.

We are working quite heavily with director at the moment and are trying to see how viable and agile it is working off the main project vs our own branch.

**Comment by ncrocfer** [comment]
Can you please signoff your commit?

**Comment by CodePint** [comment]
> Can you please signoff your commit?

Sure thing, all done.

**Pull request merged**
