### PR TITLE
feat: add description field to workflows

### PR DESCRIPTION
**Pull request by henri42**
In order to improve the monitoring experience on the UI I added a description field to the workflows table.
This way it is possible to add specific information to each workflow instance, and distinguish between the different runs.

Of course, the description is optional. 
You can run a workflow with description in three ways :

**1. Using CLI**
```bash
director workflow run product.ORDER '{"user": 1234, "product": 1000}' --description "short description here"
```
**2. Using API**
```bash
curl --header "Content-Type: application/json" \
  --request POST \
  --data '{"project": "product", "name": "ORDER", \
    "payload": {"user": 1234, "product": 1000}, \
    "description": "short description here"}' \
  http://localhost:8000/api/workflows
```

**3. Using UI, on the "Definition" page**

desc-ui

After running at least one workflow with a description you will be able to see the description in the web UI

desc-wf-list
desc-details

---

Two remarks:
- In order to add the description field, I had to add a migration in the middle of the revisions history, I am not sure that it is OK when upgrading an existing Celery-Director instance.
- The UI part of the commit might not be perfect as I am not a Vue.js specialist.

Thanks for your reading

### CODE REVIEW

**Comment by ncrocfer** [comment]
Hi @henri42,

Thank you for this PR !  We'll check it this week before giving you our feedbacks ;)

**Review by ncrocfer — CHANGES_REQUESTED** [review]
Hi @henri42 ,

Unfortunately we can not approve this PR because you update existing migrations, which is definitively not recommended :)

The problem is your code will work for new Celery Director installation, but not for existing ones (the user has already apply the migrations, your changes will not be seen).

So your new table is not available:

```
$(master) director db upgrade
INFO  [alembic.runtime.migration] Context impl SQLiteImpl.
INFO  [alembic.runtime.migration] Will assume non-transactional DDL.
INFO  [alembic.runtime.migration] Running upgrade  -> 30d6f6636351, Initial migration
INFO  [alembic.runtime.migration] Running upgrade 30d6f6636351 -> 05cf96d6fcae, Add task result
INFO  [alembic.runtime.migration] Running upgrade 05cf96d6fcae -> 3f8466b16023, Add users table
INFO  [alembic.runtime.migration] Running upgrade 3f8466b16023 -> 063ff371f2da, Add index on workflow_id in task table
INFO  [alembic.runtime.migration] Running upgrade 063ff371f2da -> 2ac615d6850b, Force varchar 255
INFO  [alembic.runtime.migration] Running upgrade 2ac615d6850b -> 46e4acde004e, Add cascade in task model for workflow deletion
$(master)  director workflow run example.ETL '{"foo": "bar"}' # <-- it works
$(master)  gh pr checkout 162  # <-- switch on your branch
Switched to branch 'wf-description'
$(wf-description)  director db upgrade # <-- your changes are not detected
INFO  [alembic.runtime.migration] Context impl SQLiteImpl.
INFO  [alembic.runtime.migration] Will assume non-transactional DDL.
$(wf-description) director db history
2ac615d6850b -> 46e4acde004e (head), Add cascade in task model for workflow deletion
063ff371f2da -> 2ac615d6850b, Force varchar 255
3f8466b16023 -> 063ff371f2da, Add index on workflow_id in task table
9d563aaa548b -> 3f8466b16023, Add users table
05cf96d6fcae -> 9d563aaa548b, Add workflows description
30d6f6636351 -> 05cf96d6fcae, Add task result
<base> -> 30d6f6636351, Initial migration
$(wf-description) director workflow run example.ETL '{"foo": "bar"}' --description "test"
Traceback (most recent call last):
  File "/Users/ncrocfer/Dev/deploy/celery-director/venv/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1245, in _execute_context
    self.dialect.do_execute(
  File "/Users/ncrocfer/Dev/deploy/celery-director/venv/lib/python3.8/site-packages/sqlalchemy/engine/default.py", line 581, in do_execute
    cursor.execute(statement, parameters)
sqlite3.OperationalError: table workflows has no column named description
[...]
```

We use [alembic](https://alembic.sqlalchemy.org/en/latest/) for the migrations, you can check [this doc](https://alembic.sqlalchemy.org/en/latest/tutorial.html#running-our-second-migration) to learn how to create new migration.

In your case I think you just have to:

- remove the changes done in the `director/migrations/versions/3f8466b16023_add_users_table.py` file
-  change the `Revises` line of your new migration file (`director/migrations/versions/9d563aaa548b_add_workflows_description.py`) to target the last known migration ID: **46e4acde004e**

**Comment by henri42** [comment]
Hi !
Thanks for your review.

If I apply the revision `9d563aaa548b_add_workflows_description.py` at the end of the history, it causes the following error when upgrading the revision `2ac615d6850b_force_varchar_255.py`.

```
sqlalchemy.exc.OperationalError: (sqlite3.OperationalError) no such column: workflows.description
[SQL: INSERT INTO _alembic_tmp_workflows (id, created_at, updated_at, name, project, status, payload, periodic, description) SELECT workflows.id, workflows.created_at, workflows.updated_at, workflows.name, workflows.project, workflows.status, workflows.payload, workflows.periodic, workflows.description 
FROM workflows]
```

After investigating, it looks like this is caused by the following block in `2ac615d6850b_force_varchar_255.py`:

```python
with op.batch_alter_table("workflows", copy_from=tables["workflows"]) as batch_op:
        batch_op.alter_column(
            "name",
            existing_type=sa.VARCHAR(),
            type_=sa.String(length=255),
            existing_nullable=False,
        )
        batch_op.alter_column(
            "project",
            existing_type=sa.VARCHAR(),
            type_=sa.String(length=255),
            existing_nullable=False,
        )
```

Indeed, when printing the columns list during the `2ac615d6850b_force_varchar_255.py` revision, the `workflows.description` column is already present before the creation of the table in the last revision `9d563aaa548b_add_workflows_description.py` :

```python
print(tables["workflows"].columns)
>>> ['workflows.id', 'workflows.created_at', 'workflows.updated_at', 'workflows.name', 'workflows.project', 'workflows.status', 'workflows.payload', 'workflows.periodic', 'workflows.description']
```
I think it is logic because it reads the table from the models in the code where the `description` column is present.

Removing the parameter `copy_from=tables["workflows"]` resolves the problem, but I saw that you added it on purpose to fix the offline mode problem with SQLite. (see #85) 

How do you think we can manage that ? Currently, it does not seem to be possible to add new columns to the existing tables on the project.

Henri

**Comment by ncrocfer** [comment]
Hi @henri42 ,

Indeed you raised a bug in Celery Director :relaxed:

I created a new issue #164 , we'll talk with the team about a possible solution. But for me the problem only comes from sqlite engine, and especially the need to generate flat SQL files.

If using the online mode of Alembic fixes this problem, but brings another one (the impossibility to add new column) I think we'll simply switch to offline mode.

I will keep you updated about the internal discussion. As a Celery Director user what do you think about it?

**Comment by ncrocfer** [comment]
Hi @henri42 ,

We finally fixed the #164 issue, sorry for the delay. Can you please rebase your branch on master ?

And can you  also change the `description` word into `comment`? Because later we'll certainly add a description field in the YAML to describe the objective of each workflow.

**Comment by henri42** [comment]
Yes, no problem I will rebase this PR soon.
Thank you for fixing the issue !

**Comment by henri42** [comment]
Hi @ncrocfer, it is rebased and the name has been fixed.

**Review by ncrocfer — APPROVED** [review]
This is very cool ! Thanks a lot for this contribution @henri42 👍

**Pull request merged**
