### PR TITLE
fix(cron) - re-order cron expression validation

### PR DESCRIPTION
**Pull request by PaulinCharliquart**
In periodic schedule expression validation, day_of_week was not is the right place

    Signed-off-by: Paulin Charliquart <paulincharliquart@gmail.com>

### CODE REVIEW

**Comment by maximecaruchet** [comment]
Hello, thank you for this pull request, however the function argument you're moving here is a named parameter, so the order does not matter anyway ^^

Also, we checked the celery documentation, and it seems that even if the argument wasn't a named parameter, the order would be fine. Here is the link to the docs:
- stable version: https://docs.celeryproject.org/en/stable/reference/celery.schedules.html#celery.schedules.crontab
- celery 4.4.0: https://docs.celeryproject.org/en/4.4.0/reference/celery.schedules.html#celery.schedules.crontab

As you can see, the function signature is `celery.schedules.crontab(minute='*', hour='*', day_of_week='*', day_of_month='*', month_of_year='*', **kwargs)`

So it seems that the order is fine even if we don't have named parameters.

**Review by PaulinCharliquart — COMMENTED** [review]
Hi Maxime,

Indeed, you're right. The error is a cron parse step. I reorder the parsing per cron order.

**Comment by maximecaruchet** [comment]
Indeed it seems that the cron parsing is incorrect. We discussed it with the team, and to avoid any breaking changes right now we suggest you update your PR to handle new parameters.

The `schedule` parameter could be kept as it is now (with the parsing problem) and 2 new parameters could be introduced to use within the `periodic` key:
* `interval` to put the time interval in seconds (like we did before with the `schedule` property)
* `crontab` with the fixed crontab syntax

This could enable the ability to indicate that the `schedule` parameter is deprecated and indicate how to migrate (along with the information that the cron syntax was fixed).

Another thing to look out for is the ability to report a problem if multiple keys are under the `periodic` key: if we start to support more than one element under `periodic`, these elements must not conflict with each other. Therefore we can only have one of `schedule`, `interval` or `crontab` as they would conflict with each other if we authorize them to be used together under the same `periodic` entry.

**Comment by PaulinCharliquart** [comment]
Hi Maxime,

I made the changes as suggested. I updated the doc to highlight the new periodic keys.

**Comment by anthonyolea** [comment]
This PR was replaced with the PR #113.

**Pull request closed without merging**
